name             'redmine'
maintainer       'Alex Crawford'
maintainer_email 'acrawford@cmdagency.com'
license          'All rights reserved'
description      'Installs/Configures redmine'
long_description 'Installs/Configures redmine'
version          '0.1.0'

depends 'lamp'
depends 'postgresql'